#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# If .bash_aliases exist, source it
if [ -f ~/.config/bash/.bash_aliases ]; then
    . ~/.config/bash/.bash_aliases
fi

# If .bash_colors exist, source it
if [ -f ~/.config/bash/.bash_colors ]; then
    . ~/.config/bash/.bash_colors
fi

# Load Xmodmap if it exists 
if [ -f ~/.config/xmodmap/.Xmodmap ]; then
    xmodmap  ~/.config/xmodmap/.Xmodmap
fi

source /usr/share/fzf/key-bindings.bash
source /usr/share/fzf/completion.bash

export EDITOR="nvim"

# color of PS1 hostname depending on hostname
if [ "$HOSTNAME" = fnord ]; then
    hostcolor="$txtblu"
elif [ "$HOSTNAME" = horus ]; then
    hostcolor="$txtpur"
else
    hostcolor="$txtylw"
fi

# color of PS1 username is red for root, else green
if [ $EUID -eq 0 ]; then
    usercolor="$txtred"
else
    usercolor="$txtgrn"
fi


PS1="\[$usercolor\]\u\[$hostcolor\]@\h\[$txtrst\] \w $\n"

