config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_init.vim:
    src: config/nvim/init.vim
    dst: ~/.config/nvim/init.vim
    link: link
  f_coc.vim:
    src: config/nvim/coc.vim
    dst: ~/.config/nvim/coc.vim
    link: link
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
    link: link
  d_xmodmap:
    src: config/xmodmap
    dst: ~/.config/xmodmap
    link: link
  d_bash:
    src: config/bash
    dst: ~/.config/bash
    link: link
  d_i3:
    src: config/i3
    dst: ~/.config/i3
    link: link
  d_git:
    src: config/git
    dst: ~/.config/git
    link: link
profiles:
  fnord:
    dotfiles:
    - f_init.vim
    - f_coc.vim
    - f_bashrc
    - d_xmodmap
    - d_bash
    - d_i3
    - d_git
