# github.com/rafi i3status config

# i3status configuration file
# see "man i3status" for documentation.

# It is important that this file is edited as UTF-8.
# The following line should contain a sharp s:
# ß
# If the above line is not correctly displayed, fix your editor first!

general {
	colors = true
	#color_good = "#97d82d"
	#color_bad = "#ff5d00"
	#color_degraded = "#55858E"
	interval = 2
}

order += "corona"
order += "spaceapi"
order += "imap"
order += "volume_status"
order += "spotify"
order += "arch_updates"
order += "whatismyip"
order += "wireless wlp3s0"
order += "ethernet enp0s25"
order += "battery_level"
order += "tztime local"

whatismyip {
    format = "🗺 {ip}"
    color = "#FFFFFF"
    color_good = "#FFFFFF"
} 

spotify {
    button_next = 4
    button_play_pause = 1
    button_previous = 5
    format = " {title} / {artist} ({time})"
    format_down = ""
    color_offline = "#FFFFFF"
    color_good = "#FFFFFF"
}

spaceapi {
    url = "https://spaceapi.reaktor23.org/"
    format = "{state} {lastchanged}"
    format_lastchanged = "%a %H:%M"
    color_closed = "#FFFFFF"
    color_open = "#00FF00"
    state_closed = "🔒"
    state_open = "🔓"
}

arch_updates {
    format = " {total}"
    hide_if_zero = True
    color = "#ff5d00"
}

battery_level {
    cache_timeout = 10
	color_bad = "#FF0000"
	color_charging = "#FCE94F"
	color_degraded = "#ff7a00"
	color_good = "#00FF00"
	format_notify_charging = "charging"
	format_notify_discharging = "discharging {percent}"
	hide_when_full = False
    hide_seconds = True
	notification = True
	notify_low_level = True
	blocks = "\uf244\uf243\uf242\uf241\uf240"
    charging_character = "\uf1e6"
	format = "{percent}% {icon} {time_remaining}"
	color_charging = "#FFFFFF"
	color_good = "#FFFFFF"
    threshold_full = 97
    threshold_degraded = 20
    threshold_bad = 10
}

imap {
    cache_timeout = 60
    server = "mail.owee.de"
    mailbox = "INBOX"
    password = "Ku3$$ab3rg2010"
    port = "993"
    user = "bouni@owee.de"
    format = "  {unseen} "
}

volume_status {
    format = "\uf025 {percentage}%"
    format_muted = "\uf025 \uf00d"
    color_muted = "#cb4b16"
    volume_delta = 1
    cache_timeout = 0.1 
    thresholds = [
        (0, "#FFFFFF"),
        (100, "#FFFFFF"),
        (101, "#FF7A00"),
    ]
}

wireless wlp3s0 {
	format_up = " %essid %quality %ip "
	format_down = ""
    color = "#FFFFFF"
    color_good = "#FFFFFF"
    color_bad = "#FFFFFF"
}

ethernet enp0s25 {
	format_up =  " %ip "
	format_down = " "
    color = "#FFFFFF"
    color_good = "#FFFFFF"
    color_bad = "#FFFFFF"
}

tztime local {
	format = " %a %d.%m.%Y %H:%M"
}
